---
title: "2021 Oxygen Drawdown"
author: "Victor Trandafir"
date: "12/5/2021"
output: github_document
---

##### This document shows an oxygen drawdown plot for the duration of the DOC remineralization expirment.

```{r message=FALSE, warning=FALSE, include=FALSE}

library(tidyverse)
library(readxl)
library(lubridate)
library(RColorBrewer)

```

```{r echo=FALSE}

delta_oxygen <- read_excel("~/Documents/College/Fourth Year/EEMB 144L/Github/144l_students_2021/Input_Data/week10/delta_oxygen.xlsx")

trial <- c("A", "B", "C", "D", "E", "F", "G", "H")

treatment <- c("Control", "Kelp Exudate", "Kelp Exudate_Nitrate_Phosphate", "Glucose_Nitrate_Phosphate")

myColors <- brewer.pal(4, "Set2")

names(myColors) <- levels(levels)

custom_colors <- scale_color_manual(name = "", values = myColors)

oxygen_drawdown <- delta_oxygen %>%
  ggplot(aes(x = days, y = change_O2_uM, color = Treatment)) +
  geom_point(size = 2.5) +
  geom_line() +
  geom_errorbar(aes(ymin = change_O2_uM - sd_change_O2_uM, ymax = change_O2_uM + sd_change_O2_uM, width = 0.1)) +
  theme_classic() +
  labs(x = "Days", y = expression(paste("Change in Oxygen (", mu, "M)")), fill = "Legend") +
  scale_x_discrete(limits = c("1", "2", "3", "4", "5", "6", "7")) +
  theme(legend.position = c(0.22, 0.25)) +
  custom_colors

oxygen_drawdown

```
